#!/usr/bin/env bash

# Assumes it lives alongside the other scripts
ROOT=$$ROOTDIR$$
BASE=`basename $0`

case "$1" in
	start)
		$ROOT/bin/es start
		$ROOT/bin/ls start
		$ROOT/bin/k start
		;;
	stop)
		$ROOT/bin/es stop
		$ROOT/bin/ls stop
		$ROOT/bin/k stop
		;;
	restart)
		$ROOT/bin/es restart
		$ROOT/bin/ls restart
		$ROOT/bin/k restart
		;;
	*)
		echo "Usage: $BASE {start|stop|restart}"
esac

echo
exit 0
